config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: "users#new"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  resources :posts, except: [:destroy] do
    resources :comments, only: [:create]
  end
  resources :users, only: [:create]
  resources :categories, except: [:destroy, :index]
end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :post_categories
has_many :posts, through: :post_categories

validates :name, presence: :true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator,  foreign_key: 'user_id', class_name: 'User' 
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator,  foreign_key: 'user_id', class_name: 'User' 
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, :url, presence: true
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :posts
has_many :comments

has_secure_password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit,:update, :show]

  def new
    @category = Category.new
  end

  def show
    @posts = @category.posts
  end

  def create
    @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "Category Created"
        redirect_to root_path
      else
        render :new
      end
  end

  def edit
    
  end

  def update
    @category.update(category_params)
    if @category.save
        flash[:notice] = "Category Created"
        redirect_to categories_path
      else
        render :new
      end
    
  end

  def destroy
    
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
   
    if @comment.save
      flash[:notice]  = "Comment created"
      redirect_to  post_path(@post)
    else 
      render 'posts/show'
    end
  end

  private

  def comment_params
        params.require(:comment).permit!
      end    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show]
  def index
    @posts = Post.all

  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)    
      
      if @post.save
        flash[:notice] = "Your post was created."
        redirect_to post_path(@post)
      else
        render :new
      end
  end

  def edit
  end

  def update
    @post.update(post_params)
    if @post.save
        flash[:notice] = "Your post was updated."
        redirect_to posts_path
      else
        render :new
      end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end
    def post_params
      params.require(:post).permit(:title,:url,:description, category_ids: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    
  end

  def destroy
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    binding.pry
    if @user.save
      flash[:notice] = "You have been registered."
      redirect_to root_path
    else 
      render :new
    end
  end

  def edit  
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_fix(str)
    str.starts_with?('http://') ? str : "http://#{str.downcase}"
  end
  def set_time(time)
      time.strftime("%A, %B %e %Y at %I:%M %P")
  end
end

app/views/categories/_form.html.erb
<%= render 'shared/errors', name: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= submit_tag "Create Category" %>
<% end -%>

app/views/categories/edit.html.erb
<%= render "shared/top_header", header_title: "Edit a category" %>
<%= render 'form'  %>

app/views/categories/index.html.erb
<%= render "shared/top_header", header_title: "List of avaiable categories" %>

<ul>
  <% @categories.each do |category|  %>
    <li>
      <%= category.name %>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<%= render "shared/top_header", header_title: "Add a new category" %>
<%= render 'form'  %>

app/views/categories/show.html.erb
<%= render "shared/top_header", header_title: "#{@category.name}" %>

<% @posts.each do |post| %>
  <div class="well">
    <h4>
      <%= post.title %>
    </h4>
    <%= render "shared/badges", name: post %>
    <p>
      <%= link_to("Read more", post_path(post)) %>
    </p>
  </div>
<% end %>
<%= render 'shared/return_nav' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>

  <div class="btn-group nav_item">
    <%= link_to '#', class: "btn btn-small dropdown-toggle", 'data-toggle' => 'dropdown', 'aria-expanded' => 'false' do %>
    Categories <span class='caret'></span>
    <% end %>
    <ul class="dropdown-menu">
      <% Category.all.each do |category| %>
        <li>
          <%= link_to("#{category.name}", category_path(category))%>
        </li>
      <% end %>
      <li class="divider"></li>
      <li>
        <%= link_to("Add New Category", new_category_path) %>
      </li>
    </ul>
  <div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', name: @post %>

<div class="row">
  <%= form_for @post do |f| %>
    <div class="row">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="row">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="row">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <br>
    <div class="row">
      <strong>Select Categories:</strong>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>
    <br>
    <br>
    <div class="row">
      <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary ')%>
    </div>
  <% end %>
</div>
<%= render 'shared/return_nav' %>

app/views/posts/edit.html.erb
<%= render "shared/top_header", header_title: "Edit Post" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render "shared/top_header", header_title: "All Posts" %>
<% @posts.each do |post| %>
  <div class="well">
    <h4>
      <%= post.title %>
    </h4>
    <p>
      <em>
        <small><%= set_time(post.created_at) %></small>
      </em>
    </p>
    <%= render "shared/badges", name: post %>
    <p>
      <%= link_to("Read more", post_path(post)) %>
    </p>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= render "shared/top_header", header_title: "Create new post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render "shared/top_header", header_title: "#{@post.title}" %>
<p>
  <strong>website:</strong> <%= url_fix(@post.url) %>
</p>

<p>
  <%= @post.description %>  
</p>
<p>
  <em>
    <small>Posted on: <%= set_time(@post.created_at) %></small>
  </em>
</p>

<%= render 'shared/errors', name: @comment %>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :body, "Add new Comment" %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit "Submit Comment" %>
<% end %>

<div class="row">
  <h5>Comments</h5>

  <% @post.comments.each do |comment| %>
    <div class="well span8">
      <em>
        "<%= comment.body %>"
      </em>
      <p>
        <em>
          <small>Posted on: <%= set_time(comment.created_at) %></small>
        </em>
      </p>
    </div>
  <% end %>
</div>
<%= render 'shared/return_nav' %>

app/views/shared/_badges.html.erb
<p>
  <% name.categories. each do |category| %>
    <span class="badge primary">
    <%= link_to("#{category.name}", category_path(category)) %>
    </span>
  <% end %>
</p>

app/views/shared/_errors.html.erb
<% if name.errors.any? %>
  <div class="alert alert-error">
    <h5>There were some errors</h5>
    <ul>
      <% name.errors.full_messages.each do |error| %>
        <li>
          <%= error %>
        </li> 
      <% end %>
    </ul>
  </div>

<% end %>

app/views/shared/_return_nav.html.erb
<div class="row">
  <%= link_to("Return to main page", root_path) %>
</div>

app/views/shared/_top_header.html.erb
<div class="page-header">
  <h1>
  <%= header_title %>
  </h1>
</div>

app/views/users/_form.html.erb
<div class="well">
<%= render 'shared/errors', name: @user %>
  <%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <br>
  <%= f.submit @user.new_record? ? "Register User" : "Update User", class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/top_header', header_title: 'Edit User' %>
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/top_header', header_title: 'Register User' %>
<%= render 'form' %>
<%= render 'shared/return_nav' %>